# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(verbose_name='date of data')),
                ('day', models.CharField(max_length=10)),
                ('sales', models.IntegerField(default=0, verbose_name='total sales')),
                ('closing_manager', models.CharField(max_length=10)),
                ('lunch_sales', models.IntegerField(default=0, verbose_name='lunch sales')),
                ('lbw', models.FloatField(default=0, verbose_name='lbw percentage')),
                ('takeaway', models.IntegerField(default=0, verbose_name='takeaway sales')),
                ('grill', models.CharField(max_length=15)),
                ('prime_acc', models.FloatField(default=0, verbose_name='Prime Accuracy')),
                ('hw', models.CharField(max_length=15)),
                ('drop', models.FloatField(default=0, verbose_name='drop variance')),
            ],
        ),
    ]
